services:
  athens.api:
    image: athens.api
    build:
      context: .
      dockerfile: Athens.Api/Dockerfile
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123